matrix:
  include:
    -language: C
    compiler:
      - gcc
      - clang
    before_script:
      - cd src/packet-sniffer
      - chmod +x build.sh build-dev.sh
    script:
      - ./build.sh
      - rm -r build
      - ./build-dev.sh
      - rm -r build

    -language: node_js
    before_script: 
      - cd src/platform/client
    script:
      - npm run build


