matrix:
  include:
    -language: C
    compiler:
      -gcc
      -clang
    before_script:
      - cd src/packet-sniffer
      - mkdir build
      - chmod +x build.sh build-dev.sh
    script:
      - ./build.sh
      - ./build-dev.sh
