matrix:
  include:
    - language: C
      compiler:
        - gcc
        - clang
      before_script:
        - cd src/packet-sniffer
        - chmod +x build.sh build-dev.sh
      script:
        - ./build.sh
        - rm -r build
        - ./build-dev.sh
        - rm -r build

    - language: node_js
      node_js:
        - 14
      before_script:
        - cd src/platform/client
        - npm install
      script:
        - npm run build

      - language: node_js
      node_js:
        - 14
      before_script:
        - cd src/platform/server
        - npm install
      script:
        - npm run start

